# Generated by Django 3.0.9 on 2021-10-16 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_auto_20211016_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Primary ID')),
                ('createdAt', models.DateTimeField(null=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('ko_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='이름')),
                ('en_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='영문 이름')),
                ('group_type', models.CharField(blank=True, choices=[('BLACKPINK', 'BLACKPINK'), ('BTS', 'BTS')], default=None, max_length=64, null=True, verbose_name='그룹 타입')),
                ('brand', models.ManyToManyField(to='common.Brand', verbose_name='브랜드')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Color', verbose_name='색상')),
            ],
            options={
                'verbose_name': '멤버',
                'verbose_name_plural': '멤버',
                'db_table': 'member_members',
                'ordering': ['id'],
            },
        ),
    ]
