# Generated by Django 3.0.9 on 2021-11-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingmall',
            name='price',
            field=models.CharField(default=0, max_length=64, verbose_name='가격'),
        ),
    ]
