#!/bin/bash

python /app/manage.py migrate --noinput
python /app/manage.py collectstatic --noinput
python /app/manage.py compilemessages

# Start gunicorn with 4 workers:
/usr/local/bin/gunicorn config.wsgi \
  -w 4 \
  -b 0.0.0.0:80 \
  --chdir=/app \
  --log-file=- \
  --log-level=info \
  --worker-tmp-dir /dev/shm
