# Generated by Django 3.0.9 on 2021-10-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_name', models.CharField(max_length=32, verbose_name='의류 카테고리 한국어')),
                ('en_name', models.CharField(max_length=32, verbose_name='의류 카테고리 영어')),
            ],
            options={
                'verbose_name': '의류 카테고리',
                'verbose_name_plural': '의류 카테고리',
                'db_table': 'cloth_category',
                'ordering': ['id'],
            },
        ),
    ]
