# Generated by Django 3.0.9 on 2021-10-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ko_name', models.CharField(max_length=32, verbose_name='의류 속성 한국어')),
                ('en_name', models.CharField(max_length=32, unique=True, verbose_name='의류 속성 영어')),
            ],
            options={
                'verbose_name': '의류 속성',
                'verbose_name_plural': '의류 속성',
                'db_table': 'cloth_attribute',
                'ordering': ['id'],
            },
        ),
    ]
