# Generated by Django 3.0.9 on 2021-10-16 07:13

import server.cloth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_auto_20211016_0605"),
        ("member", "0001_initial"),
        ("cloth", "0002_attribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clothes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Primary ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(null=True)),
                ("updatedAt", models.DateTimeField(null=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=server.cloth.models.image_upload_to,
                        verbose_name="의류 이미지",
                    ),
                ),
                (
                    "attributes",
                    models.ManyToManyField(to="cloth.Attribute", verbose_name="의류 속성"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cloth.Category",
                        verbose_name="의류 카테고리",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.Color",
                        verbose_name="의류 색상",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.Members",
                        verbose_name="멤버",
                    ),
                ),
            ],
            options={
                "verbose_name": "의류",
                "verbose_name_plural": "의류",
                "db_table": "cloth_clothes",
                "ordering": ["id"],
            },
        ),
    ]
