# Generated by Django 3.0.9 on 2021-10-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=6, unique=True, verbose_name='색상 코드')),
            ],
            options={
                'verbose_name': '색상',
                'verbose_name_plural': '색상',
                'db_table': 'color',
                'ordering': ['id'],
            },
        ),
    ]
