# Generated by Django 3.0.9 on 2021-10-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Primary ID'),
        ),
    ]
