# Generated by Django 3.0.9 on 2021-10-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20211016_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['id'], 'verbose_name': '브랜드', 'verbose_name_plural': '브랜드'},
        ),
    ]
